services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=1GB'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    pid: "host"
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
      - ./textfiles:/textfiles
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/textfiles'

  process-exporter:
    image: ncabatoff/process-exporter
    container_name: process-exporter
    pid: "host"
    ports:
      - "9256:9256"
    volumes:
      - /proc:/host/proc
      - ./process-exporter.yml:/config.yml
    command:
      - '-procfs'
      - '/host/proc'
      - '-config.path'
      - '/config.yml'
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
