global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ubuntu-node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
